#ifndef PYRAMIDWIDGETS_GLOBAL_H
#define PYRAMIDWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef PYRAMIDWIDGETS_LIB
# define PYRAMIDWIDGETS_EXPORT Q_DECL_EXPORT
#else
# define PYRAMIDWIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // PYRAMIDWIDGETS_GLOBAL_H
